# -*- coding: utf-8 -*-
"""Spotify_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOa7hbaSvzxsw6hcFhifQ9UVz3IRDFOk
"""

import os
import kagglehub
import pandas as pd

# 1. Download the dataset
path = kagglehub.dataset_download("nelgiriyewithana/top-spotify-songs-2023")

# 2. List the files in the downloaded directory to find the CSV filename
print("Downloaded files:", os.listdir(path))

# 3. Combine the path with your CSV file name (usually 'spotify-2023.csv')
csv_path = os.path.join(path, "spotify-2023.csv")

# 4. Load it into a pandas DataFrame
df = pd.read_csv(csv_path, encoding='latin1')

# 5. View the first few rows
df.head()

df.info()

print(df.shape)
print(df.size )

# Artists who have released most no. of songs.
df['artist(s)_name'].value_counts().head(5)

